#!/usr/bin/env bash

FLATBUDDY_VERSION="0.1.0"
FLATBUDDY_BINARY_NAME="flatbuddy"

set -eo pipefail

show_help()
{
	cat <<EOF
flatbuddy version: ${FLATBUDDY_VERSION}

Usage:

	${FLATBUDDY_BINARY_NAME} build
	${FLATBUDDY_BINARY_NAME} build [manifest.json, manifest.yaml, manifest.yml]
	${FLATBUDDY_BINARY_NAME} exec [manifest.json, manifest.yaml, manifest.yml] -- /bin/sh
	${FLATBUDDY_BINARY_NAME} lint [manifest.json, manifest.yaml, manifest.yml]
	${FLATBUDDY_BINARY_NAME} track [manifest.json, manifest.yaml, manifest.yml]
	${FLATBUDDY_BINARY_NAME} help
	${FLATBUDDY_BINARY_NAME} version
EOF
}

if [ $# -eq 0 ]; then
	show_help
	exit
fi

FLATBUDDY_COMMAND=$1
shift

case "${FLATBUDDY_COMMAND}" in
  "build"|"exec"|"lint"|"track")
    FLATBUDDY_PATH="$(dirname "$(realpath "${0}")")"
    "${FLATBUDDY_PATH}/flatbuddy-${FLATBUDDY_COMMAND}" "$@"
    exit 0
    ;;
  help)
    show_help
    exit 0
    ;;
  version)
    printf "${FLATBUDDY_BINARY_NAME}: %s\n" "${FLATBUDDY_VERSION}"
    exit 0
    ;;
  -*)
    printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
    show_help
    exit 1
    ;;
  *)
    show_help
    exit 1
    ;;
esac

