#!/usr/bin/env bash

FLATBUDDY_BINARY_NAME="flatbuddy"

set -eo pipefail

show_help()
{
	cat <<EOF
Usage for flatbuddy track:

	${FLATBUDDY_BINARY_NAME} track
	${FLATBUDDY_BINARY_NAME} track [manifest.json, manifest.yaml, manifest.yml]

Options:

	--user:			Run flatpak as the current user
	--dry-run:			Only print the command generated
	--verbose/--debug/-v:		Show more verbosity
	--version:			Show version
	--help/-h:			Show this help
EOF
}

while :; do
  case $1 in
    -h | --help)
      show_help
      exit 0
      ;;
    -u | --user)
      shift
      FLATBUDDY_TRACK_USER="1"
      ;;
    -n | --no-update)
      shift
      FLATBUDDY_TRACK_NO_UPDATE="1"
      ;;
    --dry-run)
      shift
      FLATBUDDY_TRACK_DRY_RUN="1"
      ;;
    -v | -d | --verbose | --debug)
      set -x
      shift
      ;;
  	--)
      shift
      FLATBUDDY_TRACK_EXTRA_ARGS="$*"
      break
      ;;
    -*)
      printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
      show_help
      exit 1
      ;;
    *)
      if [ -n "$1" ]; then
        FLATBUDDY_TARGET_MANIFEST="$1"
        shift
      else
      	break
      fi
      ;;
  esac
done

if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
  while IFS= read -r -d '' file_to_be_checked ; do \
    if yq '."app-id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null || \
      yq '."id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null; then
      export FLATBUDDY_TARGET_MANIFEST="${file_to_be_checked}"
    fi
  done < <(find . -maxdepth 1 \( -iname '*.yaml*' -o  -iname "*.yml*" -o -iname "*.json*" \) -print0)

  if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
    printf "%s" "Failed automatically detecting manifest and no manifest specified." 1>&2
    exit 1
  fi
fi 

if [ "${FLATBUDDY_TRACK_USER}" == "1" ] ; then
  FLATBUDDY_TRACK_USER_ARGUMENTS=("--user")
fi

if [ "${FLATBUDDY_TRACK_DRY_RUN}" == "1" ] ; then
  FLATBUDDY_TRACK_DRY_RUN_ARGUMENTS=("echo")
fi

if [ "${FLATBUDDY_TRACK_NO_UPDATE}" != "1" ] ; then
  FLATBUDDY_TRACK_NO_UPDATE_ARGUMENTS=("--edit-only")
fi

FLATBUDDY_TRACK_BINARY="flatpak run org.flathub.flatpak-external-data-checker"
if command -v flatpak-external-data-checker &>/dev/null ; then
  FLATBUDDY_TRACK_BINARY="flatpak-external-data-checker"
fi

${FLATBUDDY_TRACK_DRY_RUN_ARGUMENTS} ${FLATBUDDY_TRACK_BINARY} ${FLATBUDDY_TRACK_USER_ARGUMENTS} \
  "$FLATBUDDY_TARGET_MANIFEST" "${FLATBUDDY_TRACK_NO_UPDATE_ARGUMENTS}" ${FLATBUDDY_TRACK_EXTRA_ARGS}
