#!/usr/bin/env bash

FLATBUDDY_BINARY_NAME="flatbuddy"

set -eo pipefail

show_help()
{
	cat <<EOF
Usage for flatbuddy build:

	${FLATBUDDY_BINARY_NAME} build
	${FLATBUDDY_BINARY_NAME} build [manifest.json, manifest.yaml, manifest.yml]

Options:

	--no-auto:			Don't automatically install missing SDKs
	--user:			Run flatpak as the current user
	--branch:			Default Branch to be used for the output
	--bundle:			Generate flatpak bundle file at location
	--dry-run:			Only print the command generated
	--verbose/--debug/-v:		Show more verbosity
	--version:			Show version
	--help/-h:			Show this help
EOF
}

while :; do
  case $1 in
    -h | --help)
      show_help
      exit 0
      ;;
    -b | --bundle)
      if [ -n "$2" ]; then
        FLATBUDDY_BUILD_BUNDLE_DEST="$2"
        shift
        shift
      else
        exit 1
      fi
      ;;
    --bundle-oci)
      if [ "${FLATBUDDY_BUILD_BUNDLE_DEST}" == "" ]; then
        printf "%s" "Bundle OCI option must be specified with --bundle" >&2
        exit 1
      fi
      FLATBUDDY_BUILD_BUNDLE_OCI=1
      shift
      ;;
    --repo-sign)
      if [ -n "$2" ]; then
        FLATBUDDY_BUILD_REPO_SIGN_ID="$2"
        shift
        shift
      else
        exit 1
      fi
      ;;
    --no-auto)
      FLATBUDDY_BUILD_NO_AUTO_RUNTIME="1"
      shift
      ;;
    --branch)
      if [ -n "$2" ]; then
        FLATBUDDY_BUILD_DEFAULT_BRANCH="$2"
        shift
        shift
      else
        exit 1
      fi
      ;;
    --dry-run)
      shift
      FLATBUDDY_BUILD_DRY_RUN="1"
      ;;
    -u | --user)
      shift
      FLATBUDDY_BUILD_USER="1"
      ;;
    -v | -d | --verbose | --debug)
      set -x
      shift
      ;;
    -*)
      printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
      show_help
      exit 1
      ;;
    *)
      if [ -n "$1" ]; then
        FLATBUDDY_TARGET_MANIFEST="$1"
        shift
      else
      	break
      fi
      ;;
  esac
done

if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
  while IFS= read -r -d '' file_to_be_checked ; do \
    if yq '."app-id"' "${file_to_be_checked}" 2>/dev/null | grep -v "null" &>/dev/null || \
      yq '."id"' "${file_to_be_checked}" 2>/dev/null | grep -v "null" &>/dev/null; then
      export FLATBUDDY_TARGET_MANIFEST="${file_to_be_checked}"
    fi
  done < <(find . -maxdepth 1 \( -iname '*.yaml*' -o  -iname "*.yml*" -o -iname "*.json*" \) -print0)

  if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
    printf "%s" "Failed automatically detecting manifest and no manifest specified." 1>&2
    exit 1
  fi
fi 

if [ "${FLATBUDDY_BUILD_DRY_RUN}" == "1" ] ; then
  FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS=("echo")
fi

if [ "${FLATBUDDY_BUILD_USER}" == "1" ] ; then
  FLATBUDDY_BUILD_USER_ARGUMENTS=("--user")
fi

FLATBUDDY_BUILD_BINARY="flatpak run --command=flatpak-builder org.flatpak.Builder"
if command -v flatpak-builder &>/dev/null ; then
  FLATBUDDY_BUILD_BINARY="flatpak-builder"
fi

FLATBUDDY_BUILD_REPO_DIRECTORY="${FLATBUDDY_BUILD_REPO_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename $FLATBUDDY_TARGET_MANIFEST)/repo-dir}"
FLATBUDDY_BUILD_BUILD_DIRECTORY="${FLATBUDDY_BUILD_BUILD_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename "${FLATBUDDY_TARGET_MANIFEST}")/build-dir}"
FLATBUDDY_BUILD_STATE_DIRECTORY="${FLATBUDDY_BUILD_STATE_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename $FLATBUDDY_TARGET_MANIFEST)/state-dir}"

flatbuddy_bundle() {
  if [ ! -n "${FLATBUDDY_BUILD_BUNDLE_DEST}" ] ; then
    return 0
  fi

  if [ ! -d "${FLATBUDDY_BUILD_REPO_DIRECTORY}" ] ; then
    return 0
  fi

  APPID_BASE="$(basename "${FLATBUDDY_TARGET_MANIFEST}")"

  BUNDLE_ARGUMENTS=()
  if [ "${FLATBUDDY_BUILD_BUNDLE_OCI}" == 1 ] ; then
    BUNDLE_ARGUMENTS=("${BUNDLE_ARGUMENTS[@]}" "--oci")
  fi
  if [ "${FLATBUDDY_BUILD_REPO_SIGN_ID}" != "" ] ; then
    BUNDLE_ARGUMENTS=("${BUNDLE_ARGUMENTS[@]}" "--gpg-sign=${FLATBUDDY_BUILD_REPO_SIGN_ID}")    
  fi

  flatpak build-bundle "${FLATBUDDY_BUILD_REPO_DIRECTORY}" "${FLATBUDDY_BUILD_BUNDLE_DEST}" "app/${APPID_BASE%.*}/$(arch)/${FLATBUDDY_BUILD_DEFAULT_BRANCH:-stable}" "${BUNDLE_ARGUMENTS[@]}"
  exit 0
}
flatbuddy_reposign() {
  if [ ! -d "$FLATBUDDY_BUILD_REPO_DIRECTORY" ] ; then
    return 0
  fi
  if [ "${FLATBUDDY_BUILD_REPO_SIGN_ID}" == "" ] ; then
    return 0
  fi
  flatpak build-sign "${FLATBUDDY_BUILD_REPO_DIRECTORY}" "--gpg-sign=${FLATBUDDY_BUILD_REPO_SIGN_ID}" "${FLATBUDDY_BUILD_DEFAULT_BRANCH:-stable}"
}

flatbuddy_check_runtime() {
  CHECK_QUERY=$1
  shift
  
  flatpak list --json --runtime "${FLATBUDDY_BUILD_USER_ARGUMENTS[@]}" | jq -rc '.[] | "\(.application_id),\(.branch)"' | grep -E -e "${CHECK_QUERY}" &>/dev/null
}

if [ "${FLATBUDDY_BUILD_NO_AUTO_RUNTIME}" != 1 ] ; then 
  TARGET_VERSION="$(yq -rc '."runtime-version"' "${FLATBUDDY_TARGET_MANIFEST}")"

  for INSTALL_TARGET in $(yq -rc '. | "\(.runtime) \(.sdk)"' "${FLATBUDDY_TARGET_MANIFEST}") ; do
    if flatbuddy_check_runtime "${INSTALL_TARGET}.*\,.*${TARGET_VERSION}" ; then
      continue
    fi

    echo "Missing runtime to build this flatpak, installing."
    ${FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS} flatpak install "${FLATBUDDY_BUILD_USER_ARGUMENTS[@]}" "runtime/${INSTALL_TARGET}//${TARGET_VERSION}"
  done

  for INSTALL_TARGET in $(yq -rc '.sdk-extensions[]' "${FLATBUDDY_TARGET_MANIFEST}") ; do
    if flatbuddy_check_runtime "${INSTALL_TARGET}" ; then
      continue
    fi

    echo "Missing SDK to build this flatpak, installing."
    ${FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS} flatpak install "${FLATBUDDY_BUILD_USER_ARGUMENTS[@]}" "runtime/${INSTALL_TARGET}"
  done
fi

flatbuddy_bundle
flatbuddy_reposign

${FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS} ${FLATBUDDY_BUILD_BINARY} \
  ${FLATBUDDY_BUILD_USER_ARGUMENTS[@]} \
  "--default-branch=${FLATBUDDY_BUILD_DEFAULT_BRANCH:-stable}" \
  "${FLATBUDDY_BUILD_BUILD_DIRECTORY}" \
  --state-dir "${FLATBUDDY_BUILD_STATE_DIRECTORY}" \
  --repo "${FLATBUDDY_BUILD_REPO_DIRECTORY}" \
  --user \
  --ccache \
  --install \
  --force-clean \
  --disable-rofiles-fuse \
  $FLATBUDDY_TARGET_MANIFEST

flatbuddy_bundle
flatbuddy_reposign
