#!/usr/bin/env bash

FLATBUDDY_BINARY_NAME="flatbuddy"

set -eo pipefail

show_help()
{
	cat <<EOF
Usage for flatbuddy build:

	${FLATBUDDY_BINARY_NAME} build
	${FLATBUDDY_BINARY_NAME} build [manifest.json, manifest.yaml, manifest.yml]

Options:

	--branch:			Default Branch to be used for the output
	--bundle:			Generate flatpak bundle file at location
	--dry-run:			Only print the command generated
	--verbose/--debug/-v:		Show more verbosity
	--version:			Show version
	--help/-h:			Show this help
EOF
}

while :; do
  case $1 in
    -h | --help)
      show_help
      exit 0
      ;;
    -b | --bundle)
      if [ -n "$2" ]; then
        FLATBUDDY_BUILD_BUNDLE_DEST="$2"
        shift
        shift
      fi
      ;;
    --branch)
      if [ -n "$2" ]; then
        FLATBUDDY_BUILD_DEFAULT_BRANCH="$2"
        shift
        shift
      fi
      ;;
    -v | -d | --verbose | --debug)
      set -x
      shift
      ;;
    -*)
      printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
      show_help
      exit 1
      ;;
    *)
      if [ -n "$1" ]; then
        FLATBUDDY_TARGET_MANIFEST="$1"
        shift
      else
      	break
      fi
      ;;
  esac
done

if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
  while IFS= read -r -d '' file_to_be_checked ; do \
    if yq '."app-id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null || \
      yq '."id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null; then
      export FLATBUDDY_TARGET_MANIFEST="${file_to_be_checked}"
    fi
  done < <(find . -maxdepth 1 \( -iname '*.yaml*' -o  -iname "*.yml*" -o -iname "*.json*" \) -print0)

  if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
    printf "%s" "Failed automatically detecting manifest and no manifest specified." 1>&2
    exit 1
  fi
fi 

if [ "${FLATBUDDY_BUILD_DRY_RUN}" == "1" ] ; then
  FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS=("echo")
fi

FLATBUDDY_BUILD_BINARY="flatpak run --command=flatpak-builder org.flatpak.Builder"
if command -v flatpak-builder &>/dev/null ; then
  FLATBUDDY_BUILD_BINARY="flatpak-builder"
fi

FLATBUDDY_BUILD_REPO_DIRECTORY="${FLATBUDDY_BUILD_REPO_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename $FLATBUDDY_TARGET_MANIFEST)/repo-dir}"
FLATBUDDY_BUILD_BUILD_DIRECTORY="${FLATBUDDY_BUILD_BUILD_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename "${FLATBUDDY_TARGET_MANIFEST}")/build-dir}"
FLATBUDDY_BUILD_STATE_DIRECTORY="${FLATBUDDY_BUILD_STATE_DIRECTORY:-$XDG_CACHE_HOME/flatpak-builder/$(basename $FLATBUDDY_TARGET_MANIFEST)/state-dir}"

if [ -n "${FLATBUDDY_BUILD_BUNDLE_DEST}" ] && [ -d "${FLATBUDDY_BUILD_REPO_DIRECTORY}" ] ; then
  APPID_BASE="$(basename "${FLATBUDDY_TARGET_MANIFEST}")"
  flatpak build-bundle "${FLATBUDDY_BUILD_REPO_DIRECTORY}" "${FLATBUDDY_BUILD_BUNDLE_DEST}" "app/${APPID_BASE%.*}/$(arch)/${FLATBUDDY_BUILD_DEFAULT_BRANCH:-stable}"
  exit 0
fi

${FLATBUDDY_BUILD_DRY_RUN_ARGUMENTS} ${FLATBUDDY_BUILD_BINARY} \
  "--default-branch=${FLATBUDDY_BUILD_DEFAULT_BRANCH:-stable}" \
  "${FLATBUDDY_BUILD_BUILD_DIRECTORY}" \
  --state-dir "${FLATBUDDY_BUILD_STATE_DIRECTORY}" \
  --repo "${FLATBUDDY_BUILD_REPO_DIRECTORY}" \
  --user \
  --ccache \
  --install \
  --force-clean \
  --disable-rofiles-fuse \
  $FLATBUDDY_TARGET_MANIFEST

if [ -n "${FLATBUDDY_BUILD_BUNDLE_DEST}" ] && [ -d "${FLATBUDDY_BUILD_REPO_DIRECTORY}" ] ; then
  APPID_BASE="$(basename "${FLATBUDDY_TARGET_MANIFEST}")"
  flatpak build-bundle "${FLATBUDDY_BUILD_REPO_DIRECTORY}" "${FLATBUDDY_BUILD_BUNDLE_DEST}" "${APPID_BASE%.*}"
fi
