#!/usr/bin/env bash

FLATBUDDY_BINARY_NAME="flatbuddy"

set -eo pipefail

show_help()
{
	cat <<EOF
Usage for flatbuddy track:

	${FLATBUDDY_BINARY_NAME} lint
	${FLATBUDDY_BINARY_NAME} lint [manifest.json, manifest.yaml, manifest.yml]

Options:

	--user:			Run flatpak as the current user
	--dry-run:			Only print the command generated
	--verbose/--debug/-v:		Show more verbosity
	--version:			Show version
	--help/-h:			Show this help
EOF
}

while :; do
  case $1 in
    -h | --help)
      show_help
      exit 0
      ;;
    -u | --user)
      shift
      FLATBUDDY_LINT_USER="1"
      ;;
    --dry-run)
      shift
      FLATBUDDY_LINT_DRY_RUN="1"
      ;;
    -v | -d | --verbose | --debug)
      set -x
      shift
      ;;
  	--)
      shift
      FLATBUDDY_LINT_EXTRA_ARGS="$*"
      break
      ;;
    -*)
      printf >&2 "ERROR: Invalid flag '%s'\n\n" "$1"
      show_help
      exit 1
      ;;
    *)
      if [ -n "$1" ]; then
        FLATBUDDY_TARGET_MANIFEST="$1"
        shift
      else
      	break
      fi
      ;;
  esac
done

if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
  while IFS= read -r -d '' file_to_be_checked ; do \
    if yq '."app-id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null || \
      yq '."id"' "${file_to_be_checked}" | grep -v "null" &>/dev/null; then
      export FLATBUDDY_TARGET_MANIFEST="${file_to_be_checked}"
      export FLATBUDDY_LINT_ACTION="manifest"
    fi
  done < <(find . -maxdepth 1 \( -iname '*.yaml*' -o  -iname "*.yml*" -o -iname "*.json*" \) -print0)

  if [ "${FLATBUDDY_TARGET_MANIFEST}" == "" ] ; then
    printf "%s" "Failed automatically detecting manifest and no manifest specified." 1>&2
    exit 1
  fi
fi 

if [ "${FLATBUDDY_LINT_USER}" == "1" ] ; then
  FLATBUDDY_LINT_USER_ARGUMENTS=("--user")
fi

if [ "${FLATBUDDY_LINT_DRY_RUN}" == "1" ] ; then
  FLATBUDDY_LINT_DRY_RUN_ARGUMENTS=("echo")
fi

FLATBUDDY_LINT_BINARY="flatpak run --command=flatpak-builder-lint org.flatpak.Builder"
if command -v flatpak-builder-lint &>/dev/null ; then
  FLATBUDDY_LINT_BINARY="flatpak-builder-lint"
fi

${FLATBUDDY_LINT_DRY_RUN_ARGUMENTS} \
  ${FLATBUDDY_LINT_BINARY} \
  ${FLATBUDDY_LINT_USER_ARGUMENTS} \
  "${FLATBUDDY_LINT_ACTION}" \
  ${FLATBUDDY_LINT_EXTRA_ARGS} \
  "$FLATBUDDY_TARGET_MANIFEST" \
  "$@"
